# Generated by Django 4.2.11 on 2024-04-01 12:08

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cat",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    default=0,
                    validators=[
                        django.core.validators.MinValueValidator(1),
                        django.core.validators.MaxValueValidator(23),
                    ],
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
