# Generated by Django 4.2.11 on 2024-03-19 16:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cupboard",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="position",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9),
                ],
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="rack",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="last_issue_date",
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
        migrations.AlterField(
            model_name="book",
            name="max_reserve_date",
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="issue_date",
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="max_date_of_reserve",
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="return_date",
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
        migrations.AlterField(
            model_name="user",
            name="valid_till",
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
    ]
