# Generated by Django 5.0.3 on 2024-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Fiction'), (2, 'Non-Fiction')], default=0, null=True),
        ),
    ]
