# Generated by Django 4.2.11 on 2024-04-04 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="last_issue_date",
            field=models.DateField(default=datetime.date(2024, 4, 4)),
        ),
        migrations.AlterField(
            model_name="book",
            name="max_reserve_date",
            field=models.DateField(default=datetime.date(2024, 4, 4)),
        ),
        migrations.AlterField(
            model_name="req",
            name="bauthor",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="req",
            name="blink",
            field=models.CharField(default="", max_length=10000),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(default=datetime.date(2029, 4, 4)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="issue_date",
            field=models.DateField(default=datetime.date(2029, 4, 4)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="max_date_of_reserve",
            field=models.DateField(default=datetime.date(2029, 4, 4)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="return_date",
            field=models.DateField(default=datetime.date(2029, 4, 4)),
        ),
        migrations.AlterField(
            model_name="user",
            name="valid_till",
            field=models.DateField(default=datetime.date(2024, 4, 4)),
        ),
    ]
