# Generated by Django 5.0.3 on 2024-06-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_last_issue_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cat',
        ),
    ]
