# Generated by Django 5.0.3 on 2024-03-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Adventure'), (2, 'Fantasy'), (3, 'Crime'), (4, 'Classics'), (5, 'History'), (6, 'Romance'), (7, 'Biography'), (8, 'Mathematics'), (9, 'Computer Science'), (10, 'Science'), (11, 'Mechanics')], default=0, null=True),
        ),
    ]
