# Generated by Django 4.2.11 on 2024-03-21 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_book_cupboard_book_position_book_rack_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="last_issue_date",
            field=models.DateField(default=datetime.date(2024, 3, 21)),
        ),
        migrations.AlterField(
            model_name="book",
            name="max_reserve_date",
            field=models.DateField(default=datetime.date(2024, 3, 21)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(default=datetime.date(2024, 3, 21)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="issue_date",
            field=models.DateField(default=datetime.date(2024, 3, 21)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="max_date_of_reserve",
            field=models.DateField(default=datetime.date(2024, 3, 21)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="return_date",
            field=models.DateField(default=datetime.date(2024, 3, 21)),
        ),
        migrations.AlterField(
            model_name="user",
            name="valid_till",
            field=models.DateField(default=datetime.date(2024, 3, 21)),
        ),
    ]
