# Generated by Django 5.0.3 on 2024-03-13 15:44

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_available_book_last_issue_date_book_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_issue_date',
            field=models.DateField(default=datetime.date(2024, 3, 13)),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=6)),
                ('user_id', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=12)),
                ('notification', models.CharField(max_length=1000)),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Undergraduate Student'), (2, 'Postgraduate Student'), (3, 'Research Scholar'), (4, 'Faculty Member')], default=0, null=True)),
                ('max_books', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('active_no', models.IntegerField(default=0)),
                ('reserve_no', models.IntegerField(default=0)),
                ('active_books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_books', to='api.book')),
                ('reserve_books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_books', to='api.book')),
            ],
        ),
    ]
