# Generated by Django 4.2.11 on 2024-03-24 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="last_issue_date",
            field=models.DateField(default=datetime.date(2024, 3, 24)),
        ),
        migrations.AlterField(
            model_name="book",
            name="max_reserve_date",
            field=models.DateField(default=datetime.date(2024, 3, 24)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(default=datetime.date(2024, 3, 24)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="issue_date",
            field=models.DateField(default=datetime.date(2024, 3, 24)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="max_date_of_reserve",
            field=models.DateField(default=datetime.date(2024, 3, 24)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="return_date",
            field=models.DateField(default=datetime.date(2024, 3, 24)),
        ),
        migrations.AlterField(
            model_name="user",
            name="valid_till",
            field=models.DateField(default=datetime.date(2024, 3, 24)),
        ),
    ]
