# Generated by Django 4.2.11 on 2024-03-31 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_book_last_issue_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="last_issue_date",
            field=models.DateField(default=datetime.date(2024, 3, 31)),
        ),
        migrations.AlterField(
            model_name="book",
            name="max_reserve_date",
            field=models.DateField(default=datetime.date(2024, 3, 31)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(default=datetime.date(2029, 3, 31)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="issue_date",
            field=models.DateField(default=datetime.date(2029, 3, 31)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="max_date_of_reserve",
            field=models.DateField(default=datetime.date(2029, 3, 31)),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="return_date",
            field=models.DateField(default=datetime.date(2029, 3, 31)),
        ),
        migrations.AlterField(
            model_name="user",
            name="notification",
            field=models.CharField(default="0", max_length=1000),
        ),
        migrations.AlterField(
            model_name="user",
            name="valid_till",
            field=models.DateField(default=datetime.date(2029, 3, 31)),
        ),
    ]
