# Generated by Django 5.0.3 on 2024-03-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_book_last_issue_date_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=9),
        ),
    ]
