# Generated by Django 5.0.3 on 2024-03-14 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_allotisbn_remove_user_max_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_books',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2101)]),
        ),
    ]
