# Generated by Django 4.2.11 on 2024-03-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_book_last_issue_date"),
        ("api", "0008_user_max_books_alter_book_edition_alter_book_year"),
    ]

    operations = []
