# Generated by Django 5.0.3 on 2024-03-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_isbn_track_remove_user_active_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issued_code',
            field=models.CharField(default='0', max_length=9),
        ),
        migrations.AddField(
            model_name='book',
            name='reserved_code',
            field=models.CharField(default='0', max_length=9),
        ),
    ]
