# Generated by Django 5.0.3 on 2024-03-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_book_issued_code_book_reserved_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_books',
            field=models.ManyToManyField(blank=True, null=True, related_name='active_books', to='api.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='reserved_books',
            field=models.ManyToManyField(blank=True, null=True, related_name='reserved_books', to='api.book'),
        ),
    ]
