# Generated by Django 5.0.3 on 2024-03-16 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_activebooks_date_of_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activebooks',
            name='date_of_issue',
            field=models.DateField(default=datetime.date(2024, 3, 16)),
        ),
        migrations.AlterField(
            model_name='activebooks',
            name='date_of_return',
            field=models.DateField(default=datetime.date(2024, 3, 16)),
        ),
        migrations.AlterField(
            model_name='activebooks',
            name='due_date',
            field=models.DateField(default=datetime.date(2024, 3, 16)),
        ),
        migrations.AlterField(
            model_name='activebooks',
            name='max_date_of_reserve',
            field=models.DateField(default=datetime.date(2024, 3, 16)),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_issue_date',
            field=models.DateField(default=datetime.date(2024, 3, 16)),
        ),
    ]
