# Generated by Django 5.0.3 on 2024-03-16 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_active_books_user_reserved_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fine',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
