# Generated by Django 5.0.3 on 2024-03-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_activebooks_date_of_issue_and_more'),
        ('api', '0012_remove_isbn_track_remove_user_reserve_books_and_more'),
    ]

    operations = [
    ]
