# Generated by Django 5.0.3 on 2024-03-16 09:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Issue Book'), (2, 'Return Book'), (3, 'Reserve Book')], default=0, null=True)),
                ('max_date_of_reserve', models.DateField(default=datetime.date(2024, 3, 16))),
                ('issue_date', models.DateField(default=datetime.date(2024, 3, 16))),
                ('due_date', models.DateField(default=datetime.date(2024, 3, 16))),
                ('return_date', models.DateField(default=datetime.date(2024, 3, 16))),
                ('dues', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.DeleteModel(
            name='ActiveBooks',
        ),
    ]
