# Generated by Django 5.0.3 on 2024-03-17 09:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20240316_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Issue Book'), (2, 'Return Book'), (3, 'Reserve Book')], default=0, null=True)),
                ('max_date_of_reserve', models.DateField(default=datetime.date(2024, 3, 17))),
                ('issue_date', models.DateField(default=datetime.date(2024, 3, 17))),
                ('due_date', models.DateField(default=datetime.date(2024, 3, 17))),
                ('return_date', models.DateField(default=datetime.date(2024, 3, 17))),
                ('dues', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('user_code', models.CharField(default='0', max_length=9)),
                ('book_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='max_reserve_date',
            field=models.DateField(default=datetime.date(2024, 3, 17)),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_issue_date',
            field=models.DateField(default=datetime.date(2024, 3, 17)),
        ),
        migrations.AlterField(
            model_name='user',
            name='valid_till',
            field=models.DateField(default=datetime.date(2024, 3, 17)),
        ),
        migrations.DeleteModel(
            name='ActiveBooks',
        ),
    ]
