# Generated by Django 4.2.11 on 2024-03-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_transaction_book_isbn_book_max_reserve_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="transactions",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="transactions", to="api.transaction"
            ),
        ),
    ]
