# Generated by Django 5.0.3 on 2024-03-16 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_transaction_delete_activebooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='max_reserve_date',
            field=models.DateField(default=datetime.date(2024, 3, 16)),
        ),
    ]
