# Generated by Django 5.0.3 on 2024-03-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_book_max_reserve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
