# Generated by Django 5.0.3 on 2024-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_transaction_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_code',
            field=models.CharField(default='0', max_length=9),
        ),
    ]
