# Generated by Django 5.0.3 on 2024-03-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_book_last_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
    ]
